### ISSUE TITLE
Notes on setup

### ISSUE THREAD

**Issue by drewwells** [bitpay/bitpay-go#1]
Great to see a go API!

I found a few things in the instructions.

- environ.sh isn't checked into the repo
- ginkgo install instructions are missing `go get github.com/onsi/ginkgo/ginkgo`

Typically, go projects are checked out to the $GOPATH proper. Go's standard tools are very closely hooked to VCS and it makes everything a lot easier to have code in $GOPATH. This might be why the setup midway deletes everything and starts over again.

```
go get github.com/bitpay/go-bitpay
cd $GOPATH/src/github.com/bitpay/go-bitpay
git remote add origin git@github.com:<username>/go-bitpay.git
```

This can be done with just git as well by using $GOPATH as the destination: `go get github.com/bitpay/go-bitpay $GOPATH/src/github.com/bitpay`

**Comment by ionux** [comment]
Thanks for the feedback!  There's some discussion internally on how we're going to end up distributing this library while simultaneously maintaining a development branch, separate repo, etc...  If you don't mind, I'd love to open up a dialog with you off GH to pick your brain on "how things are done" in the Go community.  You look like you've done a lot with the language based on your account so I'm sure you can lend a lot of insight!  Drop an email to integrations@bitpay.com when you have a moment which will reach my entire team including the developer that's been working on this project specifically.

Thanks again!
Rich

**Comment by philosodad** [comment]
Does this issue belong here or on the bitpay-go-cli repo?

**Comment by philosodad** [comment]
Okay, so I made a couple of changes to the ReadMe to indicate that these instructions reference the reference project, not this repo. Following the instructions as written should result in a working repo with all of the test dependencies, etc.
